server:
  port: 8888
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/phone?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456


mybatis-plus:
  mapper-locations: classpath*:com/phone/**/dao/**Dao.xml
  typeAliasesPackage: com.phone.**.domain
  global-config:
    db-config:
      table-underline: true

ali:
  # OSS存储相关配置数据
  oss:
    # 存储节点
    endpoint: oss-cn-chengdu.aliyuncs.com
    bucketName: dazhiruou-test
    accessKeyId: LTAI5tFGUB8KAkot1QWJxd4y
    accessKeySecret: l63cpWcb0P4oyWUj2UhK7ZIKvSXtMz
    address: https://dazhiruou-test.oss-cn-chengdu.aliyuncs.com/
